/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Le Jardin des Langues API
 * API pour l'application d'apprentissage des langues
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DictionaryControllerSearchWordsParams
} from '../model';

import { apiClient } from '../../services/apiClient';
import type { ErrorType } from '../../services/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type dictionaryControllerSearchWordsResponse200 = {
  data: void
  status: 200
}

export type dictionaryControllerSearchWordsResponseSuccess = (dictionaryControllerSearchWordsResponse200) & {
  headers: Headers;
};
;

export type dictionaryControllerSearchWordsResponse = (dictionaryControllerSearchWordsResponseSuccess)

export const getDictionaryControllerSearchWordsUrl = (params: DictionaryControllerSearchWordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/dictionary/search?${stringifiedParams}` : `/api/v1/dictionary/search`
}

/**
 * @summary Rechercher des mots dans le dictionnaire
 */
export const dictionaryControllerSearchWords = async (params: DictionaryControllerSearchWordsParams, options?: RequestInit): Promise<dictionaryControllerSearchWordsResponse> => {

  return apiClient<dictionaryControllerSearchWordsResponse>(getDictionaryControllerSearchWordsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}




export const getDictionaryControllerSearchWordsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dictionaryControllerSearchWords>>, TError,{params: DictionaryControllerSearchWordsParams}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof dictionaryControllerSearchWords>>, TError,{params: DictionaryControllerSearchWordsParams}, TContext> => {

const mutationKey = ['dictionaryControllerSearchWords'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dictionaryControllerSearchWords>>, {params: DictionaryControllerSearchWordsParams}> = (props) => {
          const {params} = props ?? {};

          return  dictionaryControllerSearchWords(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DictionaryControllerSearchWordsMutationResult = NonNullable<Awaited<ReturnType<typeof dictionaryControllerSearchWords>>>

    export type DictionaryControllerSearchWordsMutationError = ErrorType<unknown>

    /**
 * @summary Rechercher des mots dans le dictionnaire
 */
export const useDictionaryControllerSearchWords = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dictionaryControllerSearchWords>>, TError,{params: DictionaryControllerSearchWordsParams}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dictionaryControllerSearchWords>>,
        TError,
        {params: DictionaryControllerSearchWordsParams},
        TContext
      > => {
      return useMutation(getDictionaryControllerSearchWordsMutationOptions(options), queryClient);
    }
