version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lejardin_db
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/00_init.sh
      - ./src/migrations:/docker-entrypoint-initdb.d/02_migrations
      - ./src/triggers:/docker-entrypoint-initdb.d/03_triggers
      - ./src/views:/docker-entrypoint-initdb.d/04_views
      - ./src/functions:/docker-entrypoint-initdb.d/05_functions
      - ./src/seeds:/docker-entrypoint-initdb.d/06_seeds
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
