/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Le Jardin des Langues API
 * API pour l'application d'apprentissage des langues
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import { apiClient } from '../../services/apiClient';
import type { ErrorType } from '../../services/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type flashcardsControllerGetMyFlashcardsResponse200 = {
  data: void
  status: 200
}

export type flashcardsControllerGetMyFlashcardsResponseSuccess = (flashcardsControllerGetMyFlashcardsResponse200) & {
  headers: Headers;
};
;

export type flashcardsControllerGetMyFlashcardsResponse = (flashcardsControllerGetMyFlashcardsResponseSuccess)

export const getFlashcardsControllerGetMyFlashcardsUrl = () => {




  return `/api/v1/flashcards`
}

/**
 * @summary Obtenir ses flashcards
 */
export const flashcardsControllerGetMyFlashcards = async ( options?: RequestInit): Promise<flashcardsControllerGetMyFlashcardsResponse> => {

  return apiClient<flashcardsControllerGetMyFlashcardsResponse>(getFlashcardsControllerGetMyFlashcardsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getFlashcardsControllerGetMyFlashcardsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof flashcardsControllerGetMyFlashcards>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof flashcardsControllerGetMyFlashcards>>, TError,void, TContext> => {

const mutationKey = ['flashcardsControllerGetMyFlashcards'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof flashcardsControllerGetMyFlashcards>>, void> = () => {


          return  flashcardsControllerGetMyFlashcards(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FlashcardsControllerGetMyFlashcardsMutationResult = NonNullable<Awaited<ReturnType<typeof flashcardsControllerGetMyFlashcards>>>

    export type FlashcardsControllerGetMyFlashcardsMutationError = ErrorType<unknown>

    /**
 * @summary Obtenir ses flashcards
 */
export const useFlashcardsControllerGetMyFlashcards = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof flashcardsControllerGetMyFlashcards>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof flashcardsControllerGetMyFlashcards>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getFlashcardsControllerGetMyFlashcardsMutationOptions(options), queryClient);
    }
