// Placeholder — no API endpoints available yet for the exercises feature.
// Add exercises API calls here when endpoints are generated by orval.

export const useExercisesApi = () => {
  return {};
};
