/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Le Jardin des Langues API
 * API pour l'application d'apprentissage des langues
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDto } from './userResponseDto.ts';

export interface AuthResponseDto {
  user: UserResponseDto;
  /** Indique si l'utilisateur vient d'être créé (via OAuth) */
  isNewUser: boolean;
}
