/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Le Jardin des Langues API
 * API pour l'application d'apprentissage des langues
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** Email ou nom d'utilisateur */
  emailOrUsername: string;
  /** Mot de passe */
  password: string;
}
