/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Le Jardin des Langues API
 * API pour l'application d'apprentissage des langues
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /**
     * Nom d'utilisateur unique
     * @minLength 3
     * @maxLength 50
     */
  username: string;
  /** Adresse email valide */
  email: string;
  /**
     * Mot de passe sécurisé
     * @minLength 8
     */
  password: string;
  /**
     * Nom complet de l'utilisateur
     * @maxLength 100
     */
  name: string;
  /** Code ISO 639-1 de la langue native */
  nativeLanguage: string;
  /** Code ISO 639-1 de la langue à apprendre */
  targetLanguage: string;
}
