/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Le Jardin des Langues API
 * API pour l'application d'apprentissage des langues
 * OpenAPI spec version: 1.0
 */

/**
 * Préférences utilisateur en JSON
 */
export type UpdateProfileDtoPreferences = { [key: string]: unknown };
