/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Le Jardin des Langues API
 * API pour l'application d'apprentissage des langues
 * OpenAPI spec version: 1.0
 */
import type { UpdateProfileDtoPreferences } from './updateProfileDtoPreferences.ts';

export interface UpdateProfileDto {
  /** Nom complet de l'utilisateur */
  name?: string;
  /** URL de l'avatar */
  avatarUrl?: string;
  /** Code ISO 639-1 de la langue native */
  nativeLanguage?: string;
  /** Code ISO 639-1 de la langue à apprendre */
  targetLanguage?: string;
  /** Fuseau horaire */
  timezone?: string;
  /** Préférences utilisateur en JSON */
  preferences?: UpdateProfileDtoPreferences;
}
