/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Le Jardin des Langues API
 * API pour l'application d'apprentissage des langues
 * OpenAPI spec version: 1.0
 */

export type UserResponseDtoRole = typeof UserResponseDtoRole[keyof typeof UserResponseDtoRole];


export const UserResponseDtoRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
} as const;
