/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Le Jardin des Langues API
 * API pour l'application d'apprentissage des langues
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDtoRole } from './userResponseDtoRole.ts';

export interface UserResponseDto {
  id: string;
  username: string;
  email: string;
  name: string;
  role: UserResponseDtoRole;
  avatarUrl?: string;
  nativeLanguage: string;
  targetLanguage: string;
  createdAt: string;
  updatedAt: string;
}
