/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Le Jardin des Langues API
 * API pour l'application d'apprentissage des langues
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  UpdateProfileDto
} from '../model';

import { apiClient } from '../../services/apiClient';
import type { ErrorType } from '../../services/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type usersControllerGetMyProfileResponse200 = {
  data: void
  status: 200
}

export type usersControllerGetMyProfileResponseSuccess = (usersControllerGetMyProfileResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetMyProfileResponse = (usersControllerGetMyProfileResponseSuccess)

export const getUsersControllerGetMyProfileUrl = () => {




  return `/api/v1/users/profile`
}

/**
 * @summary Obtenir son profil utilisateur
 */
export const usersControllerGetMyProfile = async ( options?: RequestInit): Promise<usersControllerGetMyProfileResponse> => {

  return apiClient<usersControllerGetMyProfileResponse>(getUsersControllerGetMyProfileUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getUsersControllerGetMyProfileMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerGetMyProfile>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerGetMyProfile>>, TError,void, TContext> => {

const mutationKey = ['usersControllerGetMyProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerGetMyProfile>>, void> = () => {


          return  usersControllerGetMyProfile(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerGetMyProfileMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetMyProfile>>>

    export type UsersControllerGetMyProfileMutationError = ErrorType<unknown>

    /**
 * @summary Obtenir son profil utilisateur
 */
export const useUsersControllerGetMyProfile = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerGetMyProfile>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerGetMyProfile>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getUsersControllerGetMyProfileMutationOptions(options), queryClient);
    }
    export type usersControllerUpdateMyProfileResponse200 = {
  data: void
  status: 200
}

export type usersControllerUpdateMyProfileResponseSuccess = (usersControllerUpdateMyProfileResponse200) & {
  headers: Headers;
};
;

export type usersControllerUpdateMyProfileResponse = (usersControllerUpdateMyProfileResponseSuccess)

export const getUsersControllerUpdateMyProfileUrl = () => {




  return `/api/v1/users/profile`
}

/**
 * @summary Mettre à jour son profil
 */
export const usersControllerUpdateMyProfile = async (updateProfileDto: UpdateProfileDto, options?: RequestInit): Promise<usersControllerUpdateMyProfileResponse> => {

  return apiClient<usersControllerUpdateMyProfileResponse>(getUsersControllerUpdateMyProfileUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateProfileDto)
  }
);}





export const getUsersControllerUpdateMyProfileQueryKey = (updateProfileDto?: UpdateProfileDto,) => {
    return [
    'PUT', `/api/v1/users/profile`, updateProfileDto
    ] as const;
    }


export const getUsersControllerUpdateMyProfileQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>, TError = ErrorType<unknown>>(updateProfileDto: UpdateProfileDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerUpdateMyProfileQueryKey(updateProfileDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>> = ({ signal }) => usersControllerUpdateMyProfile(updateProfileDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerUpdateMyProfileQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>>
export type UsersControllerUpdateMyProfileQueryError = ErrorType<unknown>


export function useUsersControllerUpdateMyProfile<TData = Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>, TError = ErrorType<unknown>>(
 updateProfileDto: UpdateProfileDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>,
          TError,
          Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerUpdateMyProfile<TData = Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>, TError = ErrorType<unknown>>(
 updateProfileDto: UpdateProfileDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>,
          TError,
          Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerUpdateMyProfile<TData = Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>, TError = ErrorType<unknown>>(
 updateProfileDto: UpdateProfileDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Mettre à jour son profil
 */

export function useUsersControllerUpdateMyProfile<TData = Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>, TError = ErrorType<unknown>>(
 updateProfileDto: UpdateProfileDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerUpdateMyProfile>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerUpdateMyProfileQueryOptions(updateProfileDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type usersControllerDeleteMyAccountResponse200 = {
  data: void
  status: 200
}

export type usersControllerDeleteMyAccountResponseSuccess = (usersControllerDeleteMyAccountResponse200) & {
  headers: Headers;
};
;

export type usersControllerDeleteMyAccountResponse = (usersControllerDeleteMyAccountResponseSuccess)

export const getUsersControllerDeleteMyAccountUrl = () => {




  return `/api/v1/users/profile`
}

/**
 * @summary Supprimer son compte
 */
export const usersControllerDeleteMyAccount = async ( options?: RequestInit): Promise<usersControllerDeleteMyAccountResponse> => {

  return apiClient<usersControllerDeleteMyAccountResponse>(getUsersControllerDeleteMyAccountUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getUsersControllerDeleteMyAccountQueryKey = () => {
    return [
    'DELETE', `/api/v1/users/profile`
    ] as const;
    }


export const getUsersControllerDeleteMyAccountQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerDeleteMyAccountQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>> = ({ signal }) => usersControllerDeleteMyAccount({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerDeleteMyAccountQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>>
export type UsersControllerDeleteMyAccountQueryError = ErrorType<unknown>


export function useUsersControllerDeleteMyAccount<TData = Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>,
          TError,
          Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerDeleteMyAccount<TData = Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>,
          TError,
          Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerDeleteMyAccount<TData = Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Supprimer son compte
 */

export function useUsersControllerDeleteMyAccount<TData = Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerDeleteMyAccount>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerDeleteMyAccountQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type usersControllerGetUserProfileResponse200 = {
  data: void
  status: 200
}

export type usersControllerGetUserProfileResponse404 = {
  data: void
  status: 404
}

export type usersControllerGetUserProfileResponseSuccess = (usersControllerGetUserProfileResponse200) & {
  headers: Headers;
};
export type usersControllerGetUserProfileResponseError = (usersControllerGetUserProfileResponse404) & {
  headers: Headers;
};

export type usersControllerGetUserProfileResponse = (usersControllerGetUserProfileResponseSuccess | usersControllerGetUserProfileResponseError)

export const getUsersControllerGetUserProfileUrl = (id: string,) => {




  return `/api/v1/users/${id}`
}

/**
 * @summary Obtenir un profil utilisateur public
 */
export const usersControllerGetUserProfile = async (id: string, options?: RequestInit): Promise<usersControllerGetUserProfileResponse> => {

  return apiClient<usersControllerGetUserProfileResponse>(getUsersControllerGetUserProfileUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}




export const getUsersControllerGetUserProfileMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerGetUserProfile>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerGetUserProfile>>, TError,{id: string}, TContext> => {

const mutationKey = ['usersControllerGetUserProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerGetUserProfile>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  usersControllerGetUserProfile(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerGetUserProfileMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetUserProfile>>>

    export type UsersControllerGetUserProfileMutationError = ErrorType<void>

    /**
 * @summary Obtenir un profil utilisateur public
 */
export const useUsersControllerGetUserProfile = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerGetUserProfile>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerGetUserProfile>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getUsersControllerGetUserProfileMutationOptions(options), queryClient);
    }
