/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Le Jardin des Langues API
 * API pour l'application d'apprentissage des langues
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthResponseDto,
  LoginDto,
  RegisterDto
} from '../model';

import { apiClient } from '../../services/apiClient';
import type { ErrorType } from '../../services/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type authControllerRegisterResponse201 = {
  data: AuthResponseDto
  status: 201
}

export type authControllerRegisterResponse409 = {
  data: void
  status: 409
}

export type authControllerRegisterResponseSuccess = (authControllerRegisterResponse201) & {
  headers: Headers;
};
export type authControllerRegisterResponseError = (authControllerRegisterResponse409) & {
  headers: Headers;
};

export type authControllerRegisterResponse = (authControllerRegisterResponseSuccess | authControllerRegisterResponseError)

export const getAuthControllerRegisterUrl = () => {




  return `/api/v1/auth/register`
}

/**
 * @summary Inscription d'un nouvel utilisateur
 */
export const authControllerRegister = async (registerDto: RegisterDto, options?: RequestInit): Promise<authControllerRegisterResponse> => {

  return apiClient<authControllerRegisterResponse>(getAuthControllerRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerDto)
  }
);}





export const getAuthControllerRegisterQueryKey = (registerDto?: RegisterDto,) => {
    return [
    'POST', `/api/v1/auth/register`, registerDto
    ] as const;
    }


export const getAuthControllerRegisterQueryOptions = <TData = Awaited<ReturnType<typeof authControllerRegister>>, TError = ErrorType<void>>(registerDto: RegisterDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerRegisterQueryKey(registerDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerRegister>>> = ({ signal }) => authControllerRegister(registerDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerRegisterQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerRegister>>>
export type AuthControllerRegisterQueryError = ErrorType<void>


export function useAuthControllerRegister<TData = Awaited<ReturnType<typeof authControllerRegister>>, TError = ErrorType<void>>(
 registerDto: RegisterDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerRegister>>,
          TError,
          Awaited<ReturnType<typeof authControllerRegister>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerRegister<TData = Awaited<ReturnType<typeof authControllerRegister>>, TError = ErrorType<void>>(
 registerDto: RegisterDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerRegister>>,
          TError,
          Awaited<ReturnType<typeof authControllerRegister>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerRegister<TData = Awaited<ReturnType<typeof authControllerRegister>>, TError = ErrorType<void>>(
 registerDto: RegisterDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Inscription d'un nouvel utilisateur
 */

export function useAuthControllerRegister<TData = Awaited<ReturnType<typeof authControllerRegister>>, TError = ErrorType<void>>(
 registerDto: RegisterDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerRegisterQueryOptions(registerDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type authControllerLoginResponse200 = {
  data: AuthResponseDto
  status: 200
}

export type authControllerLoginResponse401 = {
  data: void
  status: 401
}

export type authControllerLoginResponseSuccess = (authControllerLoginResponse200) & {
  headers: Headers;
};
export type authControllerLoginResponseError = (authControllerLoginResponse401) & {
  headers: Headers;
};

export type authControllerLoginResponse = (authControllerLoginResponseSuccess | authControllerLoginResponseError)

export const getAuthControllerLoginUrl = () => {




  return `/api/v1/auth/login`
}

/**
 * @summary Connexion d'un utilisateur
 */
export const authControllerLogin = async (loginDto: LoginDto, options?: RequestInit): Promise<authControllerLoginResponse> => {

  return apiClient<authControllerLoginResponse>(getAuthControllerLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginDto)
  }
);}





export const getAuthControllerLoginQueryKey = (loginDto?: LoginDto,) => {
    return [
    'POST', `/api/v1/auth/login`, loginDto
    ] as const;
    }


export const getAuthControllerLoginQueryOptions = <TData = Awaited<ReturnType<typeof authControllerLogin>>, TError = ErrorType<void>>(loginDto: LoginDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerLoginQueryKey(loginDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerLogin>>> = ({ signal }) => authControllerLogin(loginDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerLoginQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
export type AuthControllerLoginQueryError = ErrorType<void>


export function useAuthControllerLogin<TData = Awaited<ReturnType<typeof authControllerLogin>>, TError = ErrorType<void>>(
 loginDto: LoginDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerLogin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerLogin<TData = Awaited<ReturnType<typeof authControllerLogin>>, TError = ErrorType<void>>(
 loginDto: LoginDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerLogin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerLogin<TData = Awaited<ReturnType<typeof authControllerLogin>>, TError = ErrorType<void>>(
 loginDto: LoginDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Connexion d'un utilisateur
 */

export function useAuthControllerLogin<TData = Awaited<ReturnType<typeof authControllerLogin>>, TError = ErrorType<void>>(
 loginDto: LoginDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerLoginQueryOptions(loginDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type authControllerRefreshResponse200 = {
  data: void
  status: 200
}

export type authControllerRefreshResponse403 = {
  data: void
  status: 403
}

export type authControllerRefreshResponseSuccess = (authControllerRefreshResponse200) & {
  headers: Headers;
};
export type authControllerRefreshResponseError = (authControllerRefreshResponse403) & {
  headers: Headers;
};

export type authControllerRefreshResponse = (authControllerRefreshResponseSuccess | authControllerRefreshResponseError)

export const getAuthControllerRefreshUrl = () => {




  return `/api/v1/auth/refresh`
}

/**
 * @summary Renouveler les tokens via le refresh token
 */
export const authControllerRefresh = async ( options?: RequestInit): Promise<authControllerRefreshResponse> => {

  return apiClient<authControllerRefreshResponse>(getAuthControllerRefreshUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getAuthControllerRefreshQueryKey = () => {
    return [
    'POST', `/api/v1/auth/refresh`
    ] as const;
    }


export const getAuthControllerRefreshQueryOptions = <TData = Awaited<ReturnType<typeof authControllerRefresh>>, TError = ErrorType<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerRefreshQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerRefresh>>> = ({ signal }) => authControllerRefresh({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerRefreshQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerRefresh>>>
export type AuthControllerRefreshQueryError = ErrorType<void>


export function useAuthControllerRefresh<TData = Awaited<ReturnType<typeof authControllerRefresh>>, TError = ErrorType<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerRefresh>>,
          TError,
          Awaited<ReturnType<typeof authControllerRefresh>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerRefresh<TData = Awaited<ReturnType<typeof authControllerRefresh>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerRefresh>>,
          TError,
          Awaited<ReturnType<typeof authControllerRefresh>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerRefresh<TData = Awaited<ReturnType<typeof authControllerRefresh>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Renouveler les tokens via le refresh token
 */

export function useAuthControllerRefresh<TData = Awaited<ReturnType<typeof authControllerRefresh>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerRefreshQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type authControllerLogoutResponse204 = {
  data: void
  status: 204
}

export type authControllerLogoutResponseSuccess = (authControllerLogoutResponse204) & {
  headers: Headers;
};
;

export type authControllerLogoutResponse = (authControllerLogoutResponseSuccess)

export const getAuthControllerLogoutUrl = () => {




  return `/api/v1/auth/logout`
}

/**
 * @summary Déconnexion et invalidation de la session
 */
export const authControllerLogout = async ( options?: RequestInit): Promise<authControllerLogoutResponse> => {

  return apiClient<authControllerLogoutResponse>(getAuthControllerLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getAuthControllerLogoutQueryKey = () => {
    return [
    'POST', `/api/v1/auth/logout`
    ] as const;
    }


export const getAuthControllerLogoutQueryOptions = <TData = Awaited<ReturnType<typeof authControllerLogout>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerLogoutQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerLogout>>> = ({ signal }) => authControllerLogout({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerLogoutQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerLogout>>>
export type AuthControllerLogoutQueryError = ErrorType<unknown>


export function useAuthControllerLogout<TData = Awaited<ReturnType<typeof authControllerLogout>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerLogout>>,
          TError,
          Awaited<ReturnType<typeof authControllerLogout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerLogout<TData = Awaited<ReturnType<typeof authControllerLogout>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerLogout>>,
          TError,
          Awaited<ReturnType<typeof authControllerLogout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerLogout<TData = Awaited<ReturnType<typeof authControllerLogout>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Déconnexion et invalidation de la session
 */

export function useAuthControllerLogout<TData = Awaited<ReturnType<typeof authControllerLogout>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerLogoutQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type authControllerGoogleAuthResponse200 = {
  data: void
  status: 200
}

export type authControllerGoogleAuthResponseSuccess = (authControllerGoogleAuthResponse200) & {
  headers: Headers;
};
;

export type authControllerGoogleAuthResponse = (authControllerGoogleAuthResponseSuccess)

export const getAuthControllerGoogleAuthUrl = () => {




  return `/api/v1/auth/google`
}

/**
 * @summary Authentification avec Google
 */
export const authControllerGoogleAuth = async ( options?: RequestInit): Promise<authControllerGoogleAuthResponse> => {

  return apiClient<authControllerGoogleAuthResponse>(getAuthControllerGoogleAuthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getAuthControllerGoogleAuthMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGoogleAuth>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerGoogleAuth>>, TError,void, TContext> => {

const mutationKey = ['authControllerGoogleAuth'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerGoogleAuth>>, void> = () => {


          return  authControllerGoogleAuth(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerGoogleAuthMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerGoogleAuth>>>

    export type AuthControllerGoogleAuthMutationError = ErrorType<unknown>

    /**
 * @summary Authentification avec Google
 */
export const useAuthControllerGoogleAuth = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGoogleAuth>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerGoogleAuth>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerGoogleAuthMutationOptions(options), queryClient);
    }
    export type authControllerGoogleAuthCallbackResponse200 = {
  data: void
  status: 200
}

export type authControllerGoogleAuthCallbackResponseSuccess = (authControllerGoogleAuthCallbackResponse200) & {
  headers: Headers;
};
;

export type authControllerGoogleAuthCallbackResponse = (authControllerGoogleAuthCallbackResponseSuccess)

export const getAuthControllerGoogleAuthCallbackUrl = () => {




  return `/api/v1/auth/google/callback`
}

/**
 * @summary Callback Google OAuth
 */
export const authControllerGoogleAuthCallback = async ( options?: RequestInit): Promise<authControllerGoogleAuthCallbackResponse> => {

  return apiClient<authControllerGoogleAuthCallbackResponse>(getAuthControllerGoogleAuthCallbackUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getAuthControllerGoogleAuthCallbackMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>, TError,void, TContext> => {

const mutationKey = ['authControllerGoogleAuthCallback'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>, void> = () => {


          return  authControllerGoogleAuthCallback(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerGoogleAuthCallbackMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>>

    export type AuthControllerGoogleAuthCallbackMutationError = ErrorType<unknown>

    /**
 * @summary Callback Google OAuth
 */
export const useAuthControllerGoogleAuthCallback = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerGoogleAuthCallbackMutationOptions(options), queryClient);
    }
    export type authControllerGetProfileResponse200 = {
  data: AuthResponseDto
  status: 200
}

export type authControllerGetProfileResponse401 = {
  data: void
  status: 401
}

export type authControllerGetProfileResponseSuccess = (authControllerGetProfileResponse200) & {
  headers: Headers;
};
export type authControllerGetProfileResponseError = (authControllerGetProfileResponse401) & {
  headers: Headers;
};

export type authControllerGetProfileResponse = (authControllerGetProfileResponseSuccess | authControllerGetProfileResponseError)

export const getAuthControllerGetProfileUrl = () => {




  return `/api/v1/auth/profile`
}

/**
 * @summary Obtenir le profil de l'utilisateur connecté
 */
export const authControllerGetProfile = async ( options?: RequestInit): Promise<authControllerGetProfileResponse> => {

  return apiClient<authControllerGetProfileResponse>(getAuthControllerGetProfileUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getAuthControllerGetProfileMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError,void, TContext> => {

const mutationKey = ['authControllerGetProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerGetProfile>>, void> = () => {


          return  authControllerGetProfile(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerGetProfileMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerGetProfile>>>

    export type AuthControllerGetProfileMutationError = ErrorType<void>

    /**
 * @summary Obtenir le profil de l'utilisateur connecté
 */
export const useAuthControllerGetProfile = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerGetProfile>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerGetProfileMutationOptions(options), queryClient);
    }
