// Placeholder — no API endpoints available yet for the community feature.
// Add community API calls here when endpoints are generated by orval.

export const useCommunityApi = () => {
  return {};
};
